### PR TITLE
fix: shallow copy event param, fixes #5

### LINKED ISSUE #5: CustomEvent params would fail if they are readonly
In the following lines:
https://github.com/kumarharsh/custom-event-polyfill/blob/813029a466f0a0c7174db86656634ea2c74b1011/polyfill.js#L21-L25
the `params` object is being mutate. While this is an error, additionally, it also fails when the `params` object is constructed to be readonly.

Should instead copy the values to a new object, and then mutate the new `param` object.

### PR DESCRIPTION
**Pull request by Tal500**
fixes #5

### CODE REVIEW

File: polyfill.js [hunk 1]
```diff
@@ -20,7 +20,25 @@
...
-      params = params || {};
+
+      // We use here some version of `Object.assign` implementation, to create a shallow copy of `params`.
+      // Based on https://github.com/christiansany/object-assign-polyfill/blob/213cc63df14515fb543117059d1576204bfaa8a7/index.js
+      params = (function(from) {
+        'use strict';
+
+        var to = {};
+        // Skip over if undefined or null
+        if (from != null) {
```
Comment (kumarharsh) [inline polyfill.js]: This shouldn't be required since you're ensuring the passed parameter is never null in L40 below (`params || {}`)

File: polyfill.js [hunk 2]
```diff
@@ -20,7 +20,25 @@
   } catch (e) {
     var CustomEvent = function(event, params) {
       var evt, origPrevent;
-      params = params || {};
+
+      // We use here some version of `Object.assign` implementation, to create a shallow copy of `params`.
+      // Based on https://github.com/christiansany/object-assign-polyfill/blob/213cc63df14515fb543117059d1576204bfaa8a7/index.js
+      params = (function(from) {
```
Comment (kumarharsh) [inline polyfill.js]: Let's name this new variable `newParams` to be clear - and also because it's cleaner to not overwrite the input parameter.

**Review by kumarharsh — CHANGES_REQUESTED** [review]
.

File: polyfill.js (hunk 1 above)
Comment (Tal500) [reply polyfill.js]: It was just a simple optimization in my opinion, but I agree.
Do you want to change L40 instead to not contain `|| {}` since we're checking it already?

**Comment by Tal500** [comment]
> .

Done the changes, please check

**Comment by Tal500** [comment]
Thanks!
Can you please also release a version in NPM?
